<?php

namespace Database\Seeders;

use App\Models\Inventory;
use Illuminate\Database\Seeder;

class InventorySeeder extends Seeder
{
    protected array $inventoryItems = [
        // === ANESTESIA ===
        [
            'name' => 'Anestesia Lidocaína 2% c/epinefrina (Tubo 2.2ml)',
            'category' => 'Anestesia',
            'price' => 2500,
            'quantity' => 200,
            'low_stock_threshold' => 30,
            'unit' => 'tubos',
            'items_per_unit' => 1,
            'supplier' => 'Dentsply',
            'expiration_type' => 'Expirable',
        ],
        [
            'name' => 'Anestesia Articaína 4% c/epinefrina (Tubo 1.8ml)',
            'category' => 'Anestesia',
            'price' => 3000,
            'quantity' => 150,
            'low_stock_threshold' => 25,
            'unit' => 'tubos',
            'items_per_unit' => 1,
            'supplier' => 'Septodont',
            'expiration_type' => 'Expirable',
        ],
        [
            'name' => 'Anestesia Mepivacaína 3% s/vasoconstrictor',
            'category' => 'Anestesia',
            'price' => 2800,
            'quantity' => 100,
            'low_stock_threshold' => 20,
            'unit' => 'tubos',
            'items_per_unit' => 1,
            'supplier' => 'Septodont',
            'expiration_type' => 'Expirable',
        ],
        [
            'name' => 'Agujas de Anestesia Cortas (Caja x100)',
            'category' => 'Anestesia',
            'price' => 15000,
            'quantity' => 20,
            'low_stock_threshold' => 5,
            'unit' => 'cajas',
            'items_per_unit' => 100,
            'supplier' => 'Dentsply',
            'expiration_type' => 'Inexpirable',
        ],
        [
            'name' => 'Agujas de Anestesia Largas (Caja x100)',
            'category' => 'Anestesia',
            'price' => 15000,
            'quantity' => 20,
            'low_stock_threshold' => 5,
            'unit' => 'cajas',
            'items_per_unit' => 100,
            'supplier' => 'Dentsply',
            'expiration_type' => 'Inexpirable',
        ],
        [
            'name' => 'Cartuchos de Anestesia Vacíos (Caja x100)',
            'category' => 'Anestesia',
            'price' => 12000,
            'quantity' => 10,
            'low_stock_threshold' => 3,
            'unit' => 'cajas',
            'items_per_unit' => 100,
            'supplier' => 'Dentsply',
            'expiration_type' => 'Inexpirable',
        ],

        // === MATERIALES DE RESTAURACIÓN ===
        [
            'name' => 'Resina Filtek Z350 XT (Jeringa 4g) A2',
            'category' => 'Restauración',
            'price' => 45000,
            'quantity' => 15,
            'low_stock_threshold' => 3,
            'unit' => 'unidades',
            'items_per_unit' => 1,
            'supplier' => '3M ESPE',
            'expiration_type' => 'Expirable',
        ],
        [
            'name' => 'Resina Filtek Z350 XT (Jeringa 4g) A3',
            'category' => 'Restauración',
            'price' => 45000,
            'quantity' => 15,
            'low_stock_threshold' => 3,
            'unit' => 'unidades',
            'items_per_unit' => 1,
            'supplier' => '3M ESPE',
            'expiration_type' => 'Expirable',
        ],
        [
            'name' => 'Resina Filtek Z350 XT (Jeringa 4g) A3.5',
            'category' => 'Restauración',
            'price' => 45000,
            'quantity' => 10,
            'low_stock_threshold' => 3,
            'unit' => 'unidades',
            'items_per_unit' => 1,
            'supplier' => '3M ESPE',
            'expiration_type' => 'Expirable',
        ],
        [
            'name' => 'Resina Filtek Z350 XT (Jeringa 4g) B1',
            'category' => 'Restauración',
            'price' => 45000,
            'quantity' => 10,
            'low_stock_threshold' => 3,
            'unit' => 'unidades',
            'items_per_unit' => 1,
            'supplier' => '3M ESPE',
            'expiration_type' => 'Expirable',
        ],
        [
            'name' => 'Adhesivo Scotchbond Universal (Frasco 5ml)',
            'category' => 'Restauración',
            'price' => 65000,
            'quantity' => 8,
            'low_stock_threshold' => 2,
            'unit' => 'unidades',
            'items_per_unit' => 1,
            'supplier' => '3M ESPE',
            'expiration_type' => 'Expirable',
        ],
        [
            'name' => 'Ácido Grabador Total Etch 37% (Jeringa 3ml)',
            'category' => 'Restauración',
            'price' => 25000,
            'quantity' => 10,
            'low_stock_threshold' => 3,
            'unit' => 'unidades',
            'items_per_unit' => 1,
            'supplier' => '3M ESPE',
            'expiration_type' => 'Expirable',
        ],
        [
            'name' => 'Ionómero de Vidrio Fuji IX (Kit)',
            'category' => 'Restauración',
            'price' => 85000,
            'quantity' => 5,
            'low_stock_threshold' => 2,
            'unit' => 'kits',
            'items_per_unit' => 1,
            'supplier' => 'GC America',
            'expiration_type' => 'Expirable',
        ],
        [
            'name' => 'Base/Cemento Ionómero Fuji II LC (Kit)',
            'category' => 'Restauración',
            'price' => 90000,
            'quantity' => 4,
            'low_stock_threshold' => 2,
            'unit' => 'kits',
            'items_per_unit' => 1,
            'supplier' => 'GC America',
            'expiration_type' => 'Expirable',
        ],
        [
            'name' => 'Matrix Tofflemire + Bandas (Kit)',
            'category' => 'Restauración',
            'price' => 35000,
            'quantity' => 8,
            'low_stock_threshold' => 2,
            'unit' => 'kits',
            'items_per_unit' => 1,
            'supplier' => 'Hu-Friedy',
            'expiration_type' => 'Inexpirable',
        ],
        [
            'name' => 'Bandas Matriz Sección (Caja x100)',
            'category' => 'Restauración',
            'price' => 45000,
            'quantity' => 10,
            'low_stock_threshold' => 3,
            'unit' => 'cajas',
            'items_per_unit' => 100,
            'supplier' => '3M ESPE',
            'expiration_type' => 'Inexpirable',
        ],
        [
            'name' => 'Cuñas de Madera (Caja x200)',
            'category' => 'Restauración',
            'price' => 8000,
            'quantity' => 15,
            'low_stock_threshold' => 5,
            'unit' => 'cajas',
            'items_per_unit' => 200,
            'supplier' => 'Generico',
            'expiration_type' => 'Inexpirable',
        ],
        [
            'name' => 'Pulidores Sof-Lex (Kit)',
            'category' => 'Restauración',
            'price' => 35000,
            'quantity' => 6,
            'low_stock_threshold' => 2,
            'unit' => 'kits',
            'items_per_unit' => 1,
            'supplier' => '3M ESPE',
            'expiration_type' => 'Inexpirable',
        ],
        [
            'name' => 'Pasta de Pulir Enamel (Frasco 45g)',
            'category' => 'Restauración',
            'price' => 18000,
            'quantity' => 10,
            'low_stock_threshold' => 3,
            'unit' => 'unidades',
            'items_per_unit' => 1,
            'supplier' => 'Ivoclar',
            'expiration_type' => 'Expirable',
        ],

        // === ENDODONCIA ===
        [
            'name' => 'Limpiadores Endo K-Files (Set x6)',
            'category' => 'Endodoncia',
            'price' => 25000,
            'quantity' => 20,
            'low_stock_threshold' => 5,
            'unit' => 'sets',
            'items_per_unit' => 6,
            'supplier' => 'Dentsply Maillefer',
            'expiration_type' => 'Inexpirable',
        ],
        [
            'name' => 'Limpiadores Endo Hedstrom (Set x6)',
            'category' => 'Endodoncia',
            'price' => 25000,
            'quantity' => 15,
            'low_stock_threshold' => 5,
            'unit' => 'sets',
            'items_per_unit' => 6,
            'supplier' => 'Dentsply Maillefer',
            'expiration_type' => 'Inexpirable',
        ],
        [
            'name' => 'Limas Rotatorias ProTaper Gold (Caja x6)',
            'category' => 'Endodoncia',
            'price' => 85000,
            'quantity' => 10,
            'low_stock_threshold' => 3,
            'unit' => 'cajas',
            'items_per_unit' => 6,
            'supplier' => 'Dentsply Maillefer',
            'expiration_type' => 'Inexpirable',
        ],
        [
            'name' => 'Conos de Gutapercha ProTaper (Caja x120)',
            'category' => 'Endodoncia',
            'price' => 35000,
            'quantity' => 12,
            'low_stock_threshold' => 4,
            'unit' => 'cajas',
            'items_per_unit' => 120,
            'supplier' => 'Dentsply Maillefer',
            'expiration_type' => 'Inexpirable',
        ],
        [
            'name' => 'Conos de Gutapercha Estándar (Caja x120)',
            'category' => 'Endodoncia',
            'price' => 25000,
            'quantity' => 10,
            'low_stock_threshold' => 3,
            'unit' => 'cajas',
            'items_per_unit' => 120,
            'supplier' => 'Dentsply Maillefer',
            'expiration_type' => 'Inexpirable',
        ],
        [
            'name' => 'Cemento Sellador AH Plus (Jeringa doble)',
            'category' => 'Endodoncia',
            'price' => 55000,
            'quantity' => 8,
            'low_stock_threshold' => 2,
            'unit' => 'unidades',
            'items_per_unit' => 1,
            'supplier' => 'Dentsply Maillefer',
            'expiration_type' => 'Expirable',
        ],
        [
            'name' => 'Hipoclorito de Sodio 5.25% (Botella 500ml)',
            'category' => 'Endodoncia',
            'price' => 12000,
            'quantity' => 20,
            'low_stock_threshold' => 5,
            'unit' => 'botellas',
            'items_per_unit' => 1,
            'supplier' => 'Clorox Dental',
            'expiration_type' => 'Expirable',
        ],
        [
            'name' => 'EDTA 17% (Frasco 60ml)',
            'category' => 'Endodoncia',
            'price' => 22000,
            'quantity' => 10,
            'low_stock_threshold' => 3,
            'unit' => 'unidades',
            'items_per_unit' => 1,
            'supplier' => 'Ultradent',
            'expiration_type' => 'Expirable',
        ],
        [
            'name' => 'Clorhexidina 2% Gel (Frasco 30ml)',
            'category' => 'Endodoncia',
            'price' => 18000,
            'quantity' => 8,
            'low_stock_threshold' => 2,
            'unit' => 'unidades',
            'items_per_unit' => 1,
            'supplier' => 'Colgate',
            'expiration_type' => 'Expirable',
        ],
        [
            'name' => 'Puntos de Papel Absorbente (Caja x200)',
            'category' => 'Endodoncia',
            'price' => 15000,
            'quantity' => 15,
            'low_stock_threshold' => 5,
            'unit' => 'cajas',
            'items_per_unit' => 200,
            'supplier' => 'Dentsply Maillefer',
            'expiration_type' => 'Inexpirable',
        ],
        [
            'name' => 'Goma Dique (Caja x150 unidades)',
            'category' => 'Endodoncia',
            'price' => 35000,
            'quantity' => 8,
            'low_stock_threshold' => 2,
            'unit' => 'cajas',
            'items_per_unit' => 150,
            'supplier' => 'Coltene',
            'expiration_type' => 'Inexpirable',
        ],
        [
            'name' => 'Arco de Goma Dique (Unidad)',
            'category' => 'Endodoncia',
            'price' => 12000,
            'quantity' => 10,
            'low_stock_threshold' => 3,
            'unit' => 'unidades',
            'items_per_unit' => 1,
            'supplier' => 'Coltene',
            'expiration_type' => 'Inexpirable',
        ],
        [
            'name' => 'Clamps para Goma Dique (Set x12)',
            'category' => 'Endodoncia',
            'price' => 65000,
            'quantity' => 5,
            'low_stock_threshold' => 2,
            'unit' => 'sets',
            'items_per_unit' => 12,
            'supplier' => 'Hu-Friedy',
            'expiration_type' => 'Inexpirable',
        ],

        // === IMPRESIÓN Y MODELOS ===
        [
            'name' => 'Alginato Jeltrate Plus (Bolsa 454g)',
            'category' => 'Impresión',
            'price' => 35000,
            'quantity' => 10,
            'low_stock_threshold' => 3,
            'unit' => 'unidades',
            'items_per_unit' => 1,
            'supplier' => 'Dentsply',
            'expiration_type' => 'Expirable',
        ],
        [
            'name' => 'Silicona de Adición Extracorona (Cartucho 380ml)',
            'category' => 'Impresión',
            'price' => 95000,
            'quantity' => 6,
            'low_stock_threshold' => 2,
            'unit' => 'cartuchos',
            'items_per_unit' => 1,
            'supplier' => '3M ESPE',
            'expiration_type' => 'Expirable',
        ],
        [
            'name' => 'Silicona de Adición Intracorona (Cartucho 50ml)',
            'category' => 'Impresión',
            'price' => 65000,
            'quantity' => 8,
            'low_stock_threshold' => 2,
            'unit' => 'cartuchos',
            'items_per_unit' => 1,
            'supplier' => '3M ESPE',
            'expiration_type' => 'Expirable',
        ],
        [
            'name' => 'Yeso Tipo III (Bolsa 25kg)',
            'category' => 'Impresión',
            'price' => 45000,
            'quantity' => 5,
            'low_stock_threshold' => 2,
            'unit' => 'bolsas',
            'items_per_unit' => 1,
            'supplier' => 'Kerr',
            'expiration_type' => 'Expirable',
        ],
        [
            'name' => 'Yeso Tipo IV (Bolsa 25kg)',
            'category' => 'Impresión',
            'price' => 75000,
            'quantity' => 4,
            'low_stock_threshold' => 1,
            'unit' => 'bolsas',
            'items_per_unit' => 1,
            'supplier' => 'Kerr',
            'expiration_type' => 'Expirable',
        ],
        [
            'name' => 'Ceras de Oclusión (Paquete x12)',
            'category' => 'Impresión',
            'price' => 12000,
            'quantity' => 10,
            'low_stock_threshold' => 3,
            'unit' => 'paquetes',
            'items_per_unit' => 12,
            'supplier' => 'Generico',
            'expiration_type' => 'Inexpirable',
        ],

        // === ORTODONCIA ===
        [
            'name' => 'Brackets Metálicos MBT 0.022 (Caja x20)',
            'category' => 'Ortodoncia',
            'price' => 120000,
            'quantity' => 10,
            'low_stock_threshold' => 3,
            'unit' => 'cajas',
            'items_per_unit' => 20,
            'supplier' => '3M Unitek',
            'expiration_type' => 'Inexpirable',
        ],
        [
            'name' => 'Brackets Estéticos (Caja x20)',
            'category' => 'Ortodoncia',
            'price' => 180000,
            'quantity' => 5,
            'low_stock_threshold' => 2,
            'unit' => 'cajas',
            'items_per_unit' => 20,
            'supplier' => '3M Unitek',
            'expiration_type' => 'Inexpirable',
        ],
        [
            'name' => 'Arco Niti 0.014 (Caja x10)',
            'category' => 'Ortodoncia',
            'price' => 45000,
            'quantity' => 15,
            'low_stock_threshold' => 5,
            'unit' => 'cajas',
            'items_per_unit' => 10,
            'supplier' => '3M Unitek',
            'expiration_type' => 'Inexpirable',
        ],
        [
            'name' => 'Arco Niti 0.016 (Caja x10)',
            'category' => 'Ortodoncia',
            'price' => 45000,
            'quantity' => 15,
            'low_stock_threshold' => 5,
            'unit' => 'cajas',
            'items_per_unit' => 10,
            'supplier' => '3M Unitek',
            'expiration_type' => 'Inexpirable',
        ],
        [
            'name' => 'Arco Niti 0.018 (Caja x10)',
            'category' => 'Ortodoncia',
            'price' => 45000,
            'quantity' => 12,
            'low_stock_threshold' => 4,
            'unit' => 'cajas',
            'items_per_unit' => 10,
            'supplier' => '3M Unitek',
            'expiration_type' => 'Inexpirable',
        ],
        [
            'name' => 'Arco Acero 0.017x0.025 (Caja x10)',
            'category' => 'Ortodoncia',
            'price' => 35000,
            'quantity' => 10,
            'low_stock_threshold' => 3,
            'unit' => 'cajas',
            'items_per_unit' => 10,
            'supplier' => '3M Unitek',
            'expiration_type' => 'Inexpirable',
        ],
        [
            'name' => 'Ligaduras Elásticas (Bolsa x1000)',
            'category' => 'Ortodoncia',
            'price' => 15000,
            'quantity' => 20,
            'low_stock_threshold' => 5,
            'unit' => 'bolsas',
            'items_per_unit' => 1000,
            'supplier' => '3M Unitek',
            'expiration_type' => 'Inexpirable',
        ],
        [
            'name' => 'Elasticos Intermaxilares (Bolsa x500)',
            'category' => 'Ortodoncia',
            'price' => 12000,
            'quantity' => 15,
            'low_stock_threshold' => 5,
            'unit' => 'bolsas',
            'items_per_unit' => 500,
            'supplier' => '3M Unitek',
            'expiration_type' => 'Inexpirable',
        ],
        [
            'name' => 'Tubos Molar (Caja x20)',
            'category' => 'Ortodoncia',
            'price' => 35000,
            'quantity' => 8,
            'low_stock_threshold' => 2,
            'unit' => 'cajas',
            'items_per_unit' => 20,
            'supplier' => '3M Unitek',
            'expiration_type' => 'Inexpirable',
        ],
        [
            'name' => 'Adhesivo Transbond XT (Kit)',
            'category' => 'Ortodoncia',
            'price' => 85000,
            'quantity' => 6,
            'low_stock_threshold' => 2,
            'unit' => 'kits',
            'items_per_unit' => 1,
            'supplier' => '3M Unitek',
            'expiration_type' => 'Expirable',
        ],

        // === INFECCIÓN CONTROL / BIOSEGURIDAD ===
        [
            'name' => 'Guantes de Nitrilo (Caja x100)',
            'category' => 'Bioseguridad',
            'price' => 18000,
            'quantity' => 50,
            'low_stock_threshold' => 10,
            'unit' => 'cajas',
            'items_per_unit' => 100,
            'supplier' => '3M',
            'expiration_type' => 'Expirable',
        ],
        [
            'name' => 'Guantes de Látex (Caja x100)',
            'category' => 'Bioseguridad',
            'price' => 15000,
            'quantity' => 30,
            'low_stock_threshold' => 10,
            'unit' => 'cajas',
            'items_per_unit' => 100,
            'supplier' => '3M',
            'expiration_type' => 'Expirable',
        ],
        [
            'name' => 'Mascarillas Quirúrgicas Nivel 3 (Caja x50)',
            'category' => 'Bioseguridad',
            'price' => 25000,
            'quantity' => 40,
            'low_stock_threshold' => 10,
            'unit' => 'cajas',
            'items_per_unit' => 50,
            'supplier' => '3M',
            'expiration_type' => 'Expirable',
        ],
        [
            'name' => 'Gafas Protectoras (Unidad)',
            'category' => 'Bioseguridad',
            'price' => 12000,
            'quantity' => 20,
            'low_stock_threshold' => 5,
            'unit' => 'unidades',
            'items_per_unit' => 1,
            'supplier' => '3M',
            'expiration_type' => 'Inexpirable',
        ],
        [
            'name' => 'Delantales Desechables (Caja x50)',
            'category' => 'Bioseguridad',
            'price' => 30000,
            'quantity' => 15,
            'low_stock_threshold' => 5,
            'unit' => 'cajas',
            'items_per_unit' => 50,
            'supplier' => 'Generico',
            'expiration_type' => 'Inexpirable',
        ],
        [
            'name' => 'Baberos Desechables (Caja x200)',
            'category' => 'Bioseguridad',
            'price' => 22000,
            'quantity' => 20,
            'low_stock_threshold' => 5,
            'unit' => 'cajas',
            'items_per_unit' => 200,
            'supplier' => 'Generico',
            'expiration_type' => 'Inexpirable',
        ],
        [
            'name' => 'Fundas para Sillón Dental (Rollo x500)',
            'category' => 'Bioseguridad',
            'price' => 35000,
            'quantity' => 10,
            'low_stock_threshold' => 3,
            'unit' => 'rollos',
            'items_per_unit' => 500,
            'supplier' => 'Generico',
            'expiration_type' => 'Inexpirable',
        ],
        [
            'name' => 'Fundas para Lampara (Rollo x500)',
            'category' => 'Bioseguridad',
            'price' => 25000,
            'quantity' => 10,
            'low_stock_threshold' => 3,
            'unit' => 'rollos',
            'items_per_unit' => 500,
            'supplier' => 'Generico',
            'expiration_type' => 'Inexpirable',
        ],
        [
            'name' => 'Toallas de Papel (Rollo x6)',
            'category' => 'Bioseguridad',
            'price' => 15000,
            'quantity' => 30,
            'low_stock_threshold' => 10,
            'unit' => 'paquetes',
            'items_per_unit' => 6,
            'supplier' => 'Generico',
            'expiration_type' => 'Inexpirable',
        ],
        [
            'name' => 'Solución Desinfectante Superficie (Galón 4L)',
            'category' => 'Bioseguridad',
            'price' => 25000,
            'quantity' => 15,
            'low_stock_threshold' => 5,
            'unit' => 'galones',
            'items_per_unit' => 1,
            'supplier' => 'Diversey',
            'expiration_type' => 'Expirable',
        ],
        [
            'name' => 'Glutaraldehído 2% (Galón 4L)',
            'category' => 'Bioseguridad',
            'price' => 45000,
            'quantity' => 8,
            'low_stock_threshold' => 3,
            'unit' => 'galones',
            'items_per_unit' => 1,
            'supplier' => 'Diversey',
            'expiration_type' => 'Expirable',
        ],
        [
            'name' => 'Bolsas para Autoclave (Rollo x100)',
            'category' => 'Bioseguridad',
            'price' => 25000,
            'quantity' => 15,
            'low_stock_threshold' => 5,
            'unit' => 'rollos',
            'items_per_unit' => 100,
            'supplier' => 'Hu-Friedy',
            'expiration_type' => 'Inexpirable',
        ],
        [
            'name' => 'Indicadores Químicos Autoclave (Caja x100)',
            'category' => 'Bioseguridad',
            'price' => 18000,
            'quantity' => 10,
            'low_stock_threshold' => 3,
            'unit' => 'cajas',
            'items_per_unit' => 100,
            'supplier' => '3M',
            'expiration_type' => 'Inexpirable',
        ],

        // === INSTRUMENTAL ===
        [
            'name' => 'Espejo Bucal #5 (Unidad)',
            'category' => 'Instrumental',
            'price' => 8000,
            'quantity' => 30,
            'low_stock_threshold' => 10,
            'unit' => 'unidades',
            'items_per_unit' => 1,
            'supplier' => 'Hu-Friedy',
            'expiration_type' => 'Inexpirable',
        ],
        [
            'name' => 'Explorador #23 (Unidad)',
            'category' => 'Instrumental',
            'price' => 12000,
            'quantity' => 25,
            'low_stock_threshold' => 8,
            'unit' => 'unidades',
            'items_per_unit' => 1,
            'supplier' => 'Hu-Friedy',
            'expiration_type' => 'Inexpirable',
        ],
        [
            'name' => 'Pinza Algodonera (Unidad)',
            'category' => 'Instrumental',
            'price' => 15000,
            'quantity' => 20,
            'low_stock_threshold' => 5,
            'unit' => 'unidades',
            'items_per_unit' => 1,
            'supplier' => 'Hu-Friedy',
            'expiration_type' => 'Inexpirable',
        ],
        [
            'name' => 'Cureta Gracey (Set x14)',
            'category' => 'Instrumental',
            'price' => 180000,
            'quantity' => 5,
            'low_stock_threshold' => 2,
            'unit' => 'sets',
            'items_per_unit' => 14,
            'supplier' => 'Hu-Friedy',
            'expiration_type' => 'Inexpirable',
        ],
        [
            'name' => 'Elevador de Luxación (Unidad)',
            'category' => 'Instrumental',
            'price' => 35000,
            'quantity' => 10,
            'low_stock_threshold' => 3,
            'unit' => 'unidades',
            'items_per_unit' => 1,
            'supplier' => 'Hu-Friedy',
            'expiration_type' => 'Inexpirable',
        ],
        [
            'name' => 'Fórcex Superior (Unidad)',
            'category' => 'Instrumental',
            'price' => 65000,
            'quantity' => 8,
            'low_stock_threshold' => 2,
            'unit' => 'unidades',
            'items_per_unit' => 1,
            'supplier' => 'Hu-Friedy',
            'expiration_type' => 'Inexpirable',
        ],
        [
            'name' => 'Fórcex Inferior (Unidad)',
            'category' => 'Instrumental',
            'price' => 65000,
            'quantity' => 8,
            'low_stock_threshold' => 2,
            'unit' => 'unidades',
            'items_per_unit' => 1,
            'supplier' => 'Hu-Friedy',
            'expiration_type' => 'Inexpirable',
        ],
        [
            'name' => 'Porta Agujas Castroviejo (Unidad)',
            'category' => 'Instrumental',
            'price' => 45000,
            'quantity' => 6,
            'low_stock_threshold' => 2,
            'unit' => 'unidades',
            'items_per_unit' => 1,
            'supplier' => 'Hu-Friedy',
            'expiration_type' => 'Inexpirable',
        ],
        [
            'name' => 'Tijera Iris (Unidad)',
            'category' => 'Instrumental',
            'price' => 25000,
            'quantity' => 10,
            'low_stock_threshold' => 3,
            'unit' => 'unidades',
            'items_per_unit' => 1,
            'supplier' => 'Hu-Friedy',
            'expiration_type' => 'Inexpirable',
        ],
        [
            'name' => 'Espátula de Composite (Unidad)',
            'category' => 'Instrumental',
            'price' => 12000,
            'quantity' => 15,
            'low_stock_threshold' => 5,
            'unit' => 'unidades',
            'items_per_unit' => 1,
            'supplier' => 'Hu-Friedy',
            'expiration_type' => 'Inexpirable',
        ],

        // === FARMACIA / MEDICAMENTOS ===
        [
            'name' => 'Ibuprofeno 400mg (Caja x100)',
            'category' => 'Farmacia',
            'price' => 15000,
            'quantity' => 20,
            'low_stock_threshold' => 5,
            'unit' => 'cajas',
            'items_per_unit' => 100,
            'supplier' => 'Genérico',
            'expiration_type' => 'Expirable',
        ],
        [
            'name' => 'Acetaminofén 500mg (Caja x100)',
            'category' => 'Farmacia',
            'price' => 8000,
            'quantity' => 20,
            'low_stock_threshold' => 5,
            'unit' => 'cajas',
            'items_per_unit' => 100,
            'supplier' => 'Genérico',
            'expiration_type' => 'Expirable',
        ],
        [
            'name' => 'Amoxicilina 500mg (Caja x21)',
            'category' => 'Farmacia',
            'price' => 12000,
            'quantity' => 15,
            'low_stock_threshold' => 5,
            'unit' => 'cajas',
            'items_per_unit' => 21,
            'supplier' => 'Genérico',
            'expiration_type' => 'Expirable',
        ],
        [
            'name' => 'Clindamicina 300mg (Caja x24)',
            'category' => 'Farmacia',
            'price' => 25000,
            'quantity' => 10,
            'low_stock_threshold' => 3,
            'unit' => 'cajas',
            'items_per_unit' => 24,
            'supplier' => 'Genérico',
            'expiration_type' => 'Expirable',
        ],
        [
            'name' => 'Dexametasona 4mg (Caja x20)',
            'category' => 'Farmacia',
            'price' => 10000,
            'quantity' => 10,
            'low_stock_threshold' => 3,
            'unit' => 'cajas',
            'items_per_unit' => 20,
            'supplier' => 'Genérico',
            'expiration_type' => 'Expirable',
        ],
        [
            'name' => 'Gel de Clorhexidina 2% (Tubo 30g)',
            'category' => 'Farmacia',
            'price' => 18000,
            'quantity' => 15,
            'low_stock_threshold' => 5,
            'unit' => 'unidades',
            'items_per_unit' => 1,
            'supplier' => 'Colgate',
            'expiration_type' => 'Expirable',
        ],
        [
            'name' => 'Enjuague Bucal Clorhexidina 0.12% (Frasco 500ml)',
            'category' => 'Farmacia',
            'price' => 15000,
            'quantity' => 15,
            'low_stock_threshold' => 5,
            'unit' => 'unidades',
            'items_per_unit' => 1,
            'supplier' => 'Colgate',
            'expiration_type' => 'Expirable',
        ],

        // === RADIOLOGÍA ===
        [
            'name' => 'Película Radiográfica Periapical D (Caja x150)',
            'category' => 'Radiología',
            'price' => 85000,
            'quantity' => 10,
            'low_stock_threshold' => 3,
            'unit' => 'cajas',
            'items_per_unit' => 150,
            'supplier' => 'Dentsply',
            'expiration_type' => 'Expirable',
        ],
        [
            'name' => 'Película Radiográfica Periapical E (Caja x150)',
            'category' => 'Radiología',
            'price' => 95000,
            'quantity' => 8,
            'low_stock_threshold' => 2,
            'unit' => 'cajas',
            'items_per_unit' => 150,
            'supplier' => 'Dentsply',
            'expiration_type' => 'Expirable',
        ],
        [
            'name' => 'Revelador Radiográfico (Galón 4L)',
            'category' => 'Radiología',
            'price' => 45000,
            'quantity' => 5,
            'low_stock_threshold' => 2,
            'unit' => 'galones',
            'items_per_unit' => 1,
            'supplier' => 'Dentsply',
            'expiration_type' => 'Expirable',
        ],
        [
            'name' => 'Fijador Radiográfico (Galón 4L)',
            'category' => 'Radiología',
            'price' => 45000,
            'quantity' => 5,
            'low_stock_threshold' => 2,
            'unit' => 'galones',
            'items_per_unit' => 1,
            'supplier' => 'Dentsply',
            'expiration_type' => 'Expirable',
        ],
        [
            'name' => 'Sensores de Fosforos (Placa PSP) (Caja x50)',
            'category' => 'Radiología',
            'price' => 120000,
            'quantity' => 5,
            'low_stock_threshold' => 2,
            'unit' => 'cajas',
            'items_per_unit' => 50,
            'supplier' => 'Dentsply',
            'expiration_type' => 'Inexpirable',
        ],

        // === BLANQUEAMIENTO ===
        [
            'name' => 'Gel Blanqueamiento Opalescence 35% (Kit)',
            'category' => 'Blanqueamiento',
            'price' => 85000,
            'quantity' => 5,
            'low_stock_threshold' => 2,
            'unit' => 'kits',
            'items_per_unit' => 1,
            'supplier' => 'Ultradent',
            'expiration_type' => 'Expirable',
        ],
        [
            'name' => 'Gel Blanqueamiento Opalescence 16% (Kit)',
            'category' => 'Blanqueamiento',
            'price' => 75000,
            'quantity' => 5,
            'low_stock_threshold' => 2,
            'unit' => 'kits',
            'items_per_unit' => 1,
            'supplier' => 'Ultradent',
            'expiration_type' => 'Expirable',
        ],
        [
            'name' => 'Férulas de Blanqueamiento (Par)',
            'category' => 'Blanqueamiento',
            'price' => 15000,
            'quantity' => 20,
            'low_stock_threshold' => 5,
            'unit' => 'pares',
            'items_per_unit' => 1,
            'supplier' => 'Generico',
            'expiration_type' => 'Inexpirable',
        ],

        // === PRÓTESIS ===
        [
            'name' => 'Acrílico para Prótesis (Kit)',
            'category' => 'Prótesis',
            'price' => 65000,
            'quantity' => 5,
            'low_stock_threshold' => 2,
            'unit' => 'kits',
            'items_per_unit' => 1,
            'supplier' => 'Kerr',
            'expiration_type' => 'Expirable',
        ],
        [
            'name' => 'Cera para Prótesis (Paquete x12)',
            'category' => 'Prótesis',
            'price' => 15000,
            'quantity' => 10,
            'low_stock_threshold' => 3,
            'unit' => 'paquetes',
            'items_per_unit' => 12,
            'supplier' => 'Kerr',
            'expiration_type' => 'Inexpirable',
        ],
        [
            'name' => 'Dientes Anteriores (Set x12)',
            'category' => 'Prótesis',
            'price' => 45000,
            'quantity' => 8,
            'low_stock_threshold' => 2,
            'unit' => 'sets',
            'items_per_unit' => 12,
            'supplier' => 'Ivoclar',
            'expiration_type' => 'Inexpirable',
        ],
        [
            'name' => 'Dientes Posteriores (Set x8)',
            'category' => 'Prótesis',
            'price' => 40000,
            'quantity' => 8,
            'low_stock_threshold' => 2,
            'unit' => 'sets',
            'items_per_unit' => 8,
            'supplier' => 'Ivoclar',
            'expiration_type' => 'Inexpirable',
        ],
        [
            'name' => 'Silicona para Rebase (Kit)',
            'category' => 'Prótesis',
            'price' => 55000,
            'quantity' => 5,
            'low_stock_threshold' => 2,
            'unit' => 'kits',
            'items_per_unit' => 1,
            'supplier' => 'Kerr',
            'expiration_type' => 'Expirable',
        ],

        // === PEDODONCIA ===
        [
            'name' => 'Corona de Acero Preformada (Caja x12)',
            'category' => 'Pedodoncia',
            'price' => 85000,
            'quantity' => 5,
            'low_stock_threshold' => 2,
            'unit' => 'cajas',
            'items_per_unit' => 12,
            'supplier' => '3M ESPE',
            'expiration_type' => 'Inexpirable',
        ],
        [
            'name' => 'Mantenedor de Espacio (Unidad)',
            'category' => 'Pedodoncia',
            'price' => 15000,
            'quantity' => 10,
            'low_stock_threshold' => 3,
            'unit' => 'unidades',
            'items_per_unit' => 1,
            'supplier' => 'Generico',
            'expiration_type' => 'Inexpirable',
        ],
        [
            'name' => 'Pasta Profiláctica con Flúor (Caja x200)',
            'category' => 'Pedodoncia',
            'price' => 25000,
            'quantity' => 10,
            'low_stock_threshold' => 3,
            'unit' => 'cajas',
            'items_per_unit' => 200,
            'supplier' => '3M ESPE',
            'expiration_type' => 'Expirable',
        ],
        [
            'name' => 'Sellante de Fosas Fisuras (Jeringa 1.2g)',
            'category' => 'Pedodoncia',
            'price' => 35000,
            'quantity' => 10,
            'low_stock_threshold' => 3,
            'unit' => 'unidades',
            'items_per_unit' => 1,
            'supplier' => '3M ESPE',
            'expiration_type' => 'Expirable',
        ],
    ];

    public function run(): void
    {
        $clinicId = tenant('id') ?? \App\Models\Clinic::first()?->id;

        if (!$clinicId) {
            $this->command->error('No se encontró un tenant activo.');
            return;
        }

        foreach ($this->inventoryItems as $data) {
            Inventory::firstOrCreate(
                [
                    'clinic_id' => $clinicId,
                    'name' => $data['name'],
                ],
                $data
            );
        }

        $this->command->info('✅ ' . count($this->inventoryItems) . ' items de inventario sembrados para: ' . $clinicId);
    }
}
